### ISSUE TITLE
NLR-annotator error: Array index out of range

### ISSUE THREAD

**Issue by lufuhao** [steuernb/NLR-Annotator#15]
When I run NLR-annotator to parse NLR-Parser3.jar's output, I got following error. Is it a memory problem? All parameters are default.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
	at java.base/java.util.Vector.get(Vector.java:780)
	at nlr_annotator.NLR_Annotator.main(NLR_Annotator.java:1957)
	... 5 more
Error: NLR-Annotator.jar running error

**Comment by steuernb** [comment]
Dear lufuhao,
sorry for my late response, I was off work. 
This is not a memory problem. The key error is the "ArrayIndexOutOfBoundsException". A wild guess is that you did not run the ChopSequence step before. The shortened sequences will have identifiers with additional suffixes pointing to their position in the original sequence. If those suffixes are missing, this error occurs. Even if  your sequences are short enough (e.g. genes), you still need to run the step for Annotator to work. 
If my guess is wrong, I would need a bit more information what you are running.
all the best
Burkhard

**Comment by yike-eden** [comment]
I had the sam problem like lufuhao's.
Using meme.xml from ../software
DEBUG: Temporary directory is /share/nas1/zqd/lncrna/NLR-Annotator/process/temp_mast1
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:485)
        at nlr_parser.MastEntry.<init>(MastEntry.java:31)
        at nlr_parser.MastXMLReader.readEntry(MastXMLReader.java:97)
        at nlr_parser.MastFile.readEntries(MastFile.java:44)
        at nlr_parser.MastFile.<init>(MastFile.java:39)
        at nlr_parser.MastParallelExecuter.executeMastDNA(MastParallelExecuter.java:148)
        at nlr_parser.NLRParser.<init>(NLRParser.java:46)
        at nlr_parser.NLRParser.main(NLRParser.java:193)
        ... 5 more

**Comment by yike-eden** [comment]
I got the following error.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.sort(Arrays.java:1091)
        at java.util.Collections.sort(Collections.java:134)
        at nlr_annotator.NLR_Annotator.consolidateLists(NLR_Annotator.java:563)
        at nlr_annotator.NLR_Annotator.<init>(NLR_Annotator.java:71)
        at nlr_annotator.NLR_Annotator.main(NLR_Annotator.java:1921)
        ... 5 more

**Comment by steuernb** [comment]
Hi, if your machine allows it, provide more memory to the java virtual machine. Run it with something like
java -Xmx 4000M -jar ....
4Gb should be enough unless you have a really large sequence set. 
cheers
Burkhard
