### ISSUE TITLE
ChopSequence step error with: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ttolessa** [steuernb/NLR-Annotator#16]
Dear Burkhard,
I was annotating NLR genes for several Eucalyptus species. The program was perfectly run for most of the species but throw the following error for one of the species. It chopped only sequences on the first 4 chromosomes out of the 11 and then returned this error. I used the default value for the length of sub-sequences and overlaps. 

I would appreciate if you have a solution for this.
Thanks!

 @Error:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at nlr_annotator.ChopSequence.chop(ChopSequence.java:147)
        at nlr_annotator.ChopSequence.main(ChopSequence.java:73)
        ... 5 more

**Comment by steuernb** [comment]
Hi,
my first suspicion would be that you have a header in your fasta file that has irregularities that I have not forseen. Do you have a ">" in there without an ID? Are there any special characters in the header? 
Would you be able to share your input sequence? That can help me debugging.
cheers
Burkhard

**Comment by ttolessa** [comment]
Hi Burkhard,

I found the following irregularities:

>Chr01
>Chr02
>Chr03
>Chr04
Ctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaaaacctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaaccctaaacccta
.
.
.
.

<script>document.getElementById("cryear").innerHTML
</body>
</html>
>Chr05
>Chr06
>Chr07
>Chr08
>Chr09
>Chr10
>Chr11
>tig00003398
>tig00152279
>tig00005461
>tig00151545
>tig00005547
>tig00152259

Now get fixed them
Thank you very much for the hints!
Tamene
