### ISSUE TITLE
Problem in running NLR-annotator.jar 

### ISSUE THREAD

**Issue by Fadwa7** [steuernb/NLR-Annotator#28]
Hello Sir, 
Thank you for this software. 
i'm have a problem in running nlr-annotator.jar 

I've seen all the issues of other people and all your previous reponses helped me to run my first commands line, but i had an error in step 3 : 
**java -jar /home/fadwa/miniconda3/pkgs/NLR-Annotator.jar -i /home/fadwa/Téléchargements/Agap/Hap1/ou.nlr.xml -o /home/fadwa/Téléchargements/Agap/Hap1/NBL_annot_hap1.txt
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
_Caused by: java.lang.NumberFormatException: For input string: "Primary000000F.ver1.0.g256660.t01"_
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at nlr_annotator.NLR_Annotator.consolidateLists(NLR_Annotator.java:508)
	at nlr_annotator.NLR_Annotator.<init>(NLR_Annotator.java:71)
	at nlr_annotator.NLR_Annotator.main(NLR_Annotator.java:1933)
	... 5 more**

I replaced NLR-Parser3.jar by NLR-Parser.jar (i've seen it on one of your reply) 
and it doesn't work. Could you please help me. 

Best regards
Fadwa

**Comment by steuernb** [comment]
Hi, thanks for using NLR-Annotator!
Most of the times, I have seen the NumberFormatException, people have not used the ChopSequence before. 
If that is not the case, would you be prepared to share the commands of the steps 1 and 2 of the pipeline? Would you also be prepared to share the sequence of Primary000000F.ver1.0.g256660.t01? If that is confidential, you could run the pipeline on a few random genes, such as https://github.com/steuernb/NLR-Annotator/blob/nlr_parser3/Rgenes.CDS.fasta. Does that work?
all the best
Burkhard

**Comment by Fadwa7** [comment]
Hi, 
Thank you for response, the problem was solved by changing the PATH of my files, and the problem is caused by (**home/fadwa/Téléchargements/**) the accents ( é , è in the Téléchargements).

Best Regards.

**Comment by Songyh2022** [comment]
Hi,
Sir, I got a similar question and could not solve the problem. The commands of steps 1 and 2 of the pipeline are as follows:
step1: java -jar ~/NLR_annotation/ChopSequence.jar -i ~/data/hhy.fa -o hhy_nlr.fasta
step2: java -jar ~/NLR_annotation/NLR-Parser3.jar -t 5 -y ~/miniconda3/envs/meme/bin/mast \
-x  ~/NLR_annotation/meme.xml -i  hhy_nlr.fasta -c hhy.nlr.xml
I got the hhy.nlr.xml (116.3 MB), next, 
step3: java -jar ~/NLR_annotation/NLR-Annotator.jar -i hhy.nlr.xml -o hhy.nlr.txt , I had an error:
![image](https://user-images.githubusercontent.com/110530438/182573620-fdc39d49-8345-4bd3-8ee5-ac6333c73d12.png)

Could you please help me?

Thanks for your time!
Song

**Comment by steuernb** [comment]
Hi Song,
Could you run Annotator on another input sequence set, for example Arabidopsis chr1, please? This is to find out if the error comes from your input data or the setup.
thanks
Burkhard

**Comment by Songyh2022** [comment]
Hi Burkhard,
I apologize for the late reply. I received the same error message when ran Annotator on _Arabidopsis_ chr1 as the input sequence set. 
Best
Song

**Comment by steuernb** [comment]
From your command I can see that you are using the NLR-Parser3 from the nlr-parser3 branch. From the error message, I believe you are using the NLR-Annotator jar from the master, which is not compatible with MAST versions beyond 4.9 and NLR-Parser3. Could you please try to run the last command with this jar file that is in the same branch as NLR-Parser3? https://github.com/steuernb/NLR-Annotator/blob/nlr_parser3/NLR-Annotator.jar.
I think that should work, I hope.

**Comment by Songyh2022** [comment]
Hi Burkhard,
It is great that I sovled the problem as you said.
Thanks for taking the time!
Song

**Comment by Davidswang** [comment]
Hi Burkhard
thanks for your software
I have a problem in running NLR-Annotator-v2.1.jar for calling NLRs
#for Rgenes.cds.fa
bash>$ java -jar ../NLR-Annotator-v2.1.jar -i Rgenes_nlr.fasta -x ../mot.txt -y ../store.txt -o Rgene_nlr.txt
initialized. 0.796135218
Ran MotifParser in 3 seconds
#for protein sequence
bash>$ java -jar ../NLR-Annotator-v2.1.jar -i Rgenes_nlr2.fasta -x ../mot.txt -y ../store.txt -o Rgene_nlr2.txt
initialized. 0.7095213
Ran MotifParser in 259 seconds
java.lang.NullPointerException
        at annotator.NLR_Annotator.writeReportTxt(NLR_Annotator.java:1322)
        at annotator.NLR_Annotator.cli(NLR_Annotator.java:1903)
        at annotator.NLR_Annotator.main(NLR_Annotator.java:1954)
Does this software work with protein sequence data?

**Comment by Davidswang** [comment]
Hi Burkhard
thanks for your software
I have a problem in running NLR-Annotator-v2.1.jar for calling NLRs
#for Rgenes.cds.fa
bash>$ java -jar ../NLR-Annotator-v2.1.jar -i Rgenes_nlr.fasta -x ../mot.txt -y ../store.txt -o Rgene_nlr.txt
initialized. 0.796135218
Ran MotifParser in 3 seconds
#for protein sequence
bash>$ java -jar ../NLR-Annotator-v2.1.jar -i Rgenes_nlr2.fasta -x ../mot.txt -y ../store.txt -o Rgene_nlr2.txt
initialized. 0.7095213
Ran MotifParser in 259 seconds
java.lang.NullPointerException
        at annotator.NLR_Annotator.writeReportTxt(NLR_Annotator.java:1322)
        at annotator.NLR_Annotator.cli(NLR_Annotator.java:1903)
        at annotator.NLR_Annotator.main(NLR_Annotator.java:1954)
Does this software work with protein sequence data?

**Comment by steuernb** [comment]
Hi David,
The current version is not working with protein sequences as input. Although the internal motif search engine works on proteins, the main aim for NLR-Annotator is to find NLRs in chromosomes or other large DNA sequences. You are the second person asking this so I guess that needs to go on my todo list to implement for this version. 

Quick fix:
The version 1 of NLR-Annotator was built on NLR-Parser. NLR-Parser needs MAST from the MEME suite to run. However, that one will take protein sequences. Download here: 
https://github.com/steuernb/NLR-Annotator/blob/42e14862fe8e41e7bcd331a65359165c6f266210/NLR-Parser3.jar. 
This is from the branch nlr_parser3 (https://github.com/steuernb/NLR-Annotator/tree/nlr_parser3). If you add the option -o, you will get tabular output with NLR calls for your proteins. 

Sorry, I hope this is not too confusing. 
install MEME
Download https://github.com/steuernb/NLR-Parser/raw/master/meme.xml
java -jar NLR-Parser3.jar -t <number of threads> -y <path/to/meme/bin/mast> -x <path/to/meme.xml> -i <input.fasta> -o <output.tsv>

Please let me know if that works for you.
best wishes
Burkhard

**Comment by Davidswang** [comment]
Hi Burkhard,
thanks for your advice,
I have genome and gff data, and get cds from genome by gff files
NLR identification was performed by using Chopsequence and NLR-Annotator v2.0, that works for me
thanks a lot
best wishes
David

**Comment by Surbhigrewal** [comment]
Hi Burkhard,

Trying to run the following command on a chr-level assembly
`java -Xmx1000g -jar NLR-Annotator-v2.1b.jar -t 40 -i assembly.fasta -x mot.txt -y store.txt -o output.txt
`
but get this error

Exception in thread "main" java.lang.UnsupportedClassVersionError: annotator/NLR_Annotator : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Any idea what could be the issue?

Best wishes,
Surbhi
